// ============================================================
// IPC certificate PDF — presentation/output ONLY. Builds a print-ready,
// official-looking Interim Payment Certificate from values the engine ALREADY
// produced and renders it via the browser's print-to-PDF (zero dependency, fully
// client-side, no secrets). The browser's own text engine handles Arabic
// shaping + RTL, so it renders correctly bilingually.
//
// READS ONLY — never recomputes certified value, retention, or VAT:
//   • totals come straight off the IPC record (gross_amount / retention / vat /
//     net_payable) — the exact fields the IPC screen displays.
//   • line rows come from lineReadiness() (the same function the on-screen
//     composition uses) — { contractQty, approvedQty, rate, approvedValue }.
//   • all amounts are formatted with the app's fmt(), so they match the screen
//     character-for-character.
// ============================================================
import { fmt } from './format.js';

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
// Quantities can be fractional — show up to 2 dp, trimmed. (Amounts use fmt = rounded SAR, matching the screen.)
const qty = (n) => { const v = Number(n || 0); return v.toLocaleString('en-US', { maximumFractionDigits: 2 }); };

const TX = {
  en: {
    title: 'INTERIM PAYMENT CERTIFICATE', interim: 'Interim',
    project: 'Project / Contract', contractNo: 'Contract No.', owner: 'Owner / Employer',
    contractor: 'Contractor', consultant: 'Consultant / QS', ipcNo: 'IPC No.', period: 'Period',
    status: 'Status', certDate: 'Certified date',
    code: 'Code', desc: 'Description', unit: 'Unit', contractQty: 'Contract Qty', thisPeriod: 'This Period Qty',
    cumQty: 'Cumulative Qty', rate: 'Rate (SAR)', value: 'Certified Value (SAR)', noLines: 'No certifiable lines for this certificate.',
    gross: 'Gross value certified', retention: 'Less: Retention (10%)', subtotal: 'Sub total',
    vat: 'VAT (15%)', net: 'NET PAYABLE THIS CERTIFICATE',
    sigContractor: 'Contractor', sigConsultant: 'Consultant / Quantity Surveyor', sigEmployer: 'Owner / Employer',
    name: 'Name', signature: 'Signature', date: 'Date',
    note: 'Figures are read from the certified BoQ; this is a system-generated certificate.',
    periodNote: 'Per-line “This Period” equals cumulative for the first certificate; for later certificates the period split is shown at the certificate total, not per line.',
    generated: 'Generated by BIM QC',
  },
  ar: {
    title: 'شهادة دفعة مرحلية', interim: 'مرحلية',
    project: 'المشروع / العقد', contractNo: 'رقم العقد', owner: 'المالك / صاحب العمل',
    contractor: 'المقاول', consultant: 'الاستشاري / حصر الكميات', ipcNo: 'رقم الشهادة', period: 'الفترة',
    status: 'الحالة', certDate: 'تاريخ الاعتماد',
    code: 'الرمز', desc: 'الوصف', unit: 'الوحدة', contractQty: 'كمية العقد', thisPeriod: 'كمية هذه الفترة',
    cumQty: 'الكمية التراكمية', rate: 'السعر (ريال)', value: 'القيمة المعتمدة (ريال)', noLines: 'لا توجد بنود قابلة للاعتماد لهذه الشهادة.',
    gross: 'إجمالي القيمة المعتمدة', retention: 'ناقص: المحتجزات (10%)', subtotal: 'المجموع الفرعي',
    vat: 'ضريبة القيمة المضافة (15%)', net: 'صافي المستحق لهذه الشهادة',
    sigContractor: 'المقاول', sigConsultant: 'الاستشاري / حاصر الكميات', sigEmployer: 'المالك / صاحب العمل',
    name: 'الاسم', signature: 'التوقيع', date: 'التاريخ',
    note: 'القيم مقروءة من جدول الكميات المعتمد؛ هذه شهادة مُنشأة آلياً.',
    periodNote: 'كمية «هذه الفترة» لكل بند تساوي التراكمية للشهادة الأولى؛ وفي الشهادات اللاحقة يظهر تقسيم الفترة في إجمالي الشهادة وليس لكل بند.',
    generated: 'صادر عن BIM QC',
  },
};

/**
 * @param ipc      the IPC record (gross_amount / retention / vat / net_payable READ as-is)
 * @param project  { name, code, client, contractor, consultant }
 * @param lines    [{ code, description, unit, contractQty, approvedQty, rate, approvedValue }] (from lineReadiness)
 * @param firstCertificate  boolean — true when there are no prior certified IPCs (then per-line this-period == cumulative)
 * @param lang     'en' | 'ar'
 */
export function buildIpcCertificateHtml({ ipc = {}, project = {}, lines = [], firstCertificate = false, lang = 'en' }) {
  const rtl = lang === 'ar';
  const x = TX[rtl ? 'ar' : 'en'];

  // Totals — READ from the record exactly as the IPC screen shows them.
  const gross = Number(ipc.gross_amount || 0);
  const retention = Number(ipc.retention || 0);
  const vat = Number(ipc.vat || 0);
  const net = Number(ipc.net_payable || 0);
  const subtotal = gross - retention; // same display arithmetic as the screen (not a retention/VAT recompute)

  const kv = (label, value) => `<div class="kv"><span class="k">${esc(label)}</span><span class="v">${esc(value || '—')}</span></div>`;

  const rowsHtml = lines.length
    ? lines.map((l) => `
      <tr>
        <td class="code">${esc(l.code || '—')}</td>
        <td class="desc">${esc(l.description || '')}</td>
        <td class="u">${esc(l.unit || '')}</td>
        <td class="n">${qty(l.contractQty)}</td>
        <td class="n">${firstCertificate ? qty(l.approvedQty) : '—'}</td>
        <td class="n">${qty(l.approvedQty)}</td>
        <td class="n">${fmt(l.rate)}</td>
        <td class="n strong">${fmt(l.approvedValue)}</td>
      </tr>`).join('')
    : `<tr><td class="desc" colspan="8" style="text-align:center;color:#6b7280;padding:18px">${esc(x.noLines)}</td></tr>`;

  const totalRow = (label, value, opts = {}) => `
    <div class="tot ${opts.big ? 'big' : ''} ${opts.neg ? 'neg' : ''}">
      <span class="tl">${esc(label)}</span><span class="tv">SAR ${value}</span>
    </div>`;

  const sigBlock = (role) => `
    <div class="sig">
      <div class="sig-role">${esc(role)}</div>
      <div class="sig-line"><span>${esc(x.name)}</span></div>
      <div class="sig-line"><span>${esc(x.signature)}</span></div>
      <div class="sig-line"><span>${esc(x.date)}</span></div>
    </div>`;

  const html = `<!doctype html>
<html lang="${rtl ? 'ar' : 'en'}" dir="${rtl ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8">
<title>${esc(ipc.ipc_number || 'IPC')} — ${esc(x.title)}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Cairo:wght@400;600;700&display=swap" rel="stylesheet">
<style>
  @page { size: A4 portrait; margin: 14mm 12mm; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: ${rtl ? "'Cairo'," : ''} 'Inter', system-ui, Arial, sans-serif; color: #1f2430; font-size: 11px; }
  .doc { max-width: 186mm; margin: 0 auto; }
  .topbar { background: #0b1f4d; color: #fff; padding: 12px 16px; border-bottom: 3px solid #1d4ed8; display: flex; justify-content: space-between; align-items: center; }
  .topbar h1 { font-size: 16px; margin: 0; font-weight: 700; letter-spacing: .3px; }
  .topbar .ipcno { font-size: 12px; font-weight: 600; opacity: .9; }
  .brand { font-size: 10px; opacity: .8; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 0 24px; padding: 12px 16px; border: 1px solid #d9dee7; border-top: none; }
  .kv { display: flex; justify-content: space-between; gap: 10px; padding: 3px 0; border-bottom: 1px dotted #e5e7eb; }
  .kv .k { color: #6b7280; } .kv .v { font-weight: 600; text-align: ${rtl ? 'left' : 'right'}; }
  table { width: 100%; border-collapse: collapse; margin-top: 14px; }
  thead th { background: #eaf1ff; color: #0b1f4d; font-weight: 700; font-size: 10px; padding: 7px 6px; border: 1px solid #d9dee7; text-align: ${rtl ? 'right' : 'left'}; }
  thead th.n { text-align: ${rtl ? 'left' : 'right'}; }
  tbody td { padding: 5px 6px; border: 1px solid #e5e7eb; vertical-align: top; }
  tbody tr:nth-child(even) td { background: #f6f8fb; }
  td.n { text-align: ${rtl ? 'left' : 'right'}; font-variant-numeric: tabular-nums; white-space: nowrap; }
  td.code { font-weight: 600; color: #1d4ed8; white-space: nowrap; }
  td.u { color: #6b7280; } td.strong { font-weight: 700; }
  .summary { display: flex; justify-content: ${rtl ? 'flex-start' : 'flex-end'}; margin-top: 14px; }
  .totals { width: 280px; border: 1px solid #d9dee7; }
  .tot { display: flex; justify-content: space-between; padding: 6px 12px; border-bottom: 1px solid #eef1f6; }
  .tot .tl { color: #374151; } .tot .tv { font-weight: 600; font-variant-numeric: tabular-nums; }
  .tot.neg .tv { color: #b91c1c; }
  .tot.big { background: #eaf1ff; border-top: 2px solid #1d4ed8; border-bottom: none; }
  .tot.big .tl { font-weight: 700; color: #0b1f4d; } .tot.big .tv { font-weight: 800; color: #1d4ed8; font-size: 13px; }
  .sigs { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 18px; margin-top: 34px; page-break-inside: avoid; }
  .sig-role { font-weight: 700; color: #0b1f4d; margin-bottom: 26px; font-size: 11px; }
  .sig-line { border-top: 1px solid #9ca3af; margin-top: 20px; padding-top: 3px; color: #6b7280; font-size: 10px; }
  .foot { margin-top: 22px; padding-top: 8px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 9px; display: flex; justify-content: space-between; gap: 12px; }
  .note { color: #6b7280; font-size: 9px; margin-top: 6px; }
</style>
</head>
<body>
  <div class="doc">
    <div class="topbar">
      <div>
        <h1>${esc(x.title)}</h1>
        <div class="brand">${esc(project.name || '')}${project.code ? ' · ' + esc(project.code) : ''}</div>
      </div>
      <div class="ipcno">${esc(x.ipcNo)} ${esc(ipc.ipc_number || '—')}</div>
    </div>
    <div class="meta">
      <div>
        ${kv(x.project, project.name)}
        ${kv(x.contractNo, project.code)}
        ${kv(x.owner, project.client)}
      </div>
      <div>
        ${kv(x.contractor, project.contractor)}
        ${kv(x.consultant, project.consultant)}
        ${kv(x.period, ipc.period)}
        ${kv(x.status, (ipc.status || '').toString().toUpperCase())}
        ${kv(x.certDate, ipc.cert_date)}
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>${esc(x.code)}</th><th>${esc(x.desc)}</th><th>${esc(x.unit)}</th>
          <th class="n">${esc(x.contractQty)}</th><th class="n">${esc(x.thisPeriod)}</th>
          <th class="n">${esc(x.cumQty)}</th><th class="n">${esc(x.rate)}</th><th class="n">${esc(x.value)}</th>
        </tr>
      </thead>
      <tbody>${rowsHtml}</tbody>
    </table>

    <div class="summary">
      <div class="totals">
        ${totalRow(x.gross, fmt(gross))}
        ${totalRow(x.retention, '(' + fmt(retention) + ')', { neg: true })}
        ${totalRow(x.subtotal, fmt(subtotal))}
        ${totalRow(x.vat, fmt(vat))}
        ${totalRow(x.net, fmt(net), { big: true })}
      </div>
    </div>

    <div class="sigs">
      ${sigBlock(x.sigContractor)}
      ${sigBlock(x.sigConsultant)}
      ${sigBlock(x.sigEmployer)}
    </div>

    ${!firstCertificate ? `<div class="note">${esc(x.periodNote)}</div>` : ''}
    <div class="foot">
      <span>${esc(x.note)}</span>
      <span>${esc(x.generated)}</span>
    </div>
  </div>
</body>
</html>`;

  return html;
}

/** Build the certificate and print it (browser print-to-PDF). Read-only. */
export function printIpcCertificate(opts) {
  const html = buildIpcCertificateHtml(opts);
  // Print via a hidden iframe — avoids popup blockers and keeps the app page intact.
  const iframe = document.createElement('iframe');
  iframe.setAttribute('aria-hidden', 'true');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);
  const doc = iframe.contentWindow?.document;
  if (!doc) { iframe.remove(); return false; }
  doc.open(); doc.write(html); doc.close();
  const fire = () => { try { iframe.contentWindow.focus(); iframe.contentWindow.print(); } catch { /* ignore */ } };
  // Give the document + webfonts a moment, then print; clean up afterwards.
  iframe.onload = () => setTimeout(fire, 350);
  setTimeout(() => { try { iframe.remove(); } catch { /* ignore */ } }, 60000);
  return true;
}
